[loggers]
keys=root,flask_app

[handlers]
keys=queueHandler,consoleHandler,fileHandler

[formatters]
keys=simpleFormatter

[logger_root]
level=DEBUG
handlers=queueHandler

[logger_flask_app]
level=DEBUG
handlers=queueHandler
qualname=app
propagate=0

[handler_queueHandler]
class=logging.handlers.QueueHandler
level=DEBUG
args=(log_queue,)

[handler_consoleHandler]
class=StreamHandler
level=DEBUG
formatter=simpleFormatter
args=(sys.stdout,)

[handler_fileHandler]
class=handlers.RotatingFileHandler
level=DEBUG
formatter=simpleFormatter
args=('%(LOG_FILE)s', 'a', %(MAX_BYTES)d, %(BACKUP_COUNT)d)
defaults={'LOG_FILE': 'flask_app.log', 'MAX_BYTES': 10485760, 'BACKUP_COUNT': 7}

[formatter_simpleFormatter]
format=%(asctime)s [%(levelname)s] %(name)s: %(message)s
datefmt=%Y-%m-%d %H:%M:%S