// components/Reviews.tsx

export default function Reviews({ count }: { count: number }) {
    const numReviews = Math.min(count, 10);

    //Sample reviews generated by AI (Grok) based on my prompt of Jaina's first review
    const reviews = [
        {
            text: "I used this service to plan my trip back to Menethil Harbor, and it made things painless! Except for the encroaching orcs, anyway... But that's not the service's fault!",
            author: "Jaina Proudmoore",
        },
        {
            text: "Booking a stay in Orgrimmar was a breeze. The guide even warned me about the heat—perfect for a tauren like me!",
            author: "Baine Bloodhoof",
        },
        {
            text: "The interactive map helped me navigate the plaguelands. Still got lost, but at least I looked stylish doing it.",
            author: "Sylvanas Windrunner",
        },
        {
            text: "Found the best taverns in Stormwind thanks to this guide. The ale recommendations were spot on!",
            author: "Anduin Wrynn",
        },
        {
            text: "Tried to visit the Barrens. Service was great, but the chatty kodo herds weren’t in the brochure!",
            author: "Thrall",
        },
        {
            text: "Azeroth Tour Guide got me to Darnassus before the tree burned. Timing was impeccable!",
            author: "Tyrande Whisperwind",
        },
        {
            text: "Planned a raid on Blackrock Mountain. The tips on avoiding lava were a lifesaver—literally.",
            author: "Varian Wrynn",
        },
        {
            text: "The Eastern Kingdoms tour was flawless. Even got to dodge some pesky Defias bandits!",
            author: "Khadgar",
        },
        {
            text: "Booked a trip to Thunder Bluff. The scenic lift ride was a highlight—highly recommend!",
            author: "Cairne Bloodhoof",
        },
        {
            text: "Explored Kalimdor with ease. The guide didn’t mention murlocs, but I survived!",
            author: "Vol’jin",
        },
    ];

    return (
        <div className="bg-gray-900 py-6">
            <h3 className="p-4 text-3xl font-extrabold text-amber-400 mx-auto text-center drop-shadow-[2px_2px_0px_black]">
                Read our reviews!
            </h3>
            <div className="max-w-4xl mx-auto space-y-6 py-6">
                {reviews.slice(0, numReviews).map((review, index) => (
                    <div
                        key={index}
                        className="bg-gray-800 p-6 rounded-xl shadow-lg text-gray-300 text-center border border-indigo-600"
                    >
                        <p className="mb-2 italic text-lg">"{review.text}"</p>
                        <p className="text-amber-500 font-semibold text-lg">— {review.author}</p>
                    </div>
                ))}
            </div>
        </div>
    );
}